name: Deploy Frontend to EC2

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      # ğŸ”‘ .env.production ìƒì„±
      - name: Create .env.production
        run: |
          echo "REACT_APP_TURN_URL=${{ secrets.REACT_APP_TURN_URL }}" >> frontend/.env.production
          echo "REACT_APP_TURN_USERNAME=${{ secrets.REACT_APP_TURN_USERNAME }}" >> frontend/.env.production
          echo "REACT_APP_TURN_PASSWORD=${{ secrets.REACT_APP_TURN_PASSWORD }}" >> frontend/.env.production
          cat .env.production  # âœ… í™•ì¸ìš© (ë¡œê·¸ì—ëŠ” ***ë¡œ ë§ˆìŠ¤í‚¹ë¨)

      - name: Build
        run: npm run build
        env:
          CI: false   # lint ì—ëŸ¬ ë¹Œë“œ ì‹¤íŒ¨ ë°©ì§€

      - name: Prepare frontend build folder
        run: |
          rm -rf frontend-build
          mkdir frontend-build
          cp -r build/. frontend-build/    # dist/ ì˜ ë‚´ìš© ëª¨ë‘ ë³µì‚¬

      - name: Deploy via SCP to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "frontend-build/*"
          target: "~/frontend-temp"

      - name: SSH into EC2 and move files with sudo
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo mv ~/frontend-temp/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
            sudo systemctl reload nginx
